name: rx_connectivity_checker_example
description: A robust, reactive Dart/Flutter package for monitoring network connectivity.

publish_to: 'none'

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  dev: ^1.0.0
  flutter:
    sdk: flutter
  rx_connectivity_checker:
    path: ../
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0