name: rx_connectivity_checker
description: "A robust, reactive Dart/Flutter package for monitoring network connectivity."
version: 0.3.0
repository: https://github.com/lorenacimpean/rx_connectivity_checker

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  dev: ^1.0.0
  flutter:
    sdk: flutter
  http: ^1.6.0
  mocktail: ^1.0.4
  project_starter_kit: ^1.0.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  coverage: ^1.15.0


